# Generated by Django 4.2.6 on 2023-10-19 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('price_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price_Cost')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sale_Price')),
                ('stock', models.PositiveSmallIntegerField(verbose_name='Stock')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.category')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'product',
            },
        ),
    ]
