# Generated by Django 4.2.6 on 2023-10-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_alert',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Min Alert'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Stock'),
        ),
    ]
