# Generated by Django 4.2.6 on 2023-10-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateField(auto_now=True, null=True, verbose_name='Updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/logos/', verbose_name='Company Logo')),
                ('company_name', models.CharField(max_length=125, verbose_name='Company Name')),
                ('reference_contact', models.CharField(max_length=125, verbose_name='Reference Contact')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone')),
                ('nit', models.CharField(max_length=15, verbose_name='NIT')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'Providers',
            },
        ),
    ]
