# Generated by Django 4.2.6 on 2023-10-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='nit',
            field=models.CharField(blank=True, default='C/F', max_length=25, null=True, unique=True, verbose_name='NIT'),
        ),
    ]
