# Generated by Django 4.2.6 on 2023-10-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total'),
        ),
    ]
