# Generated by Django 4.2.6 on 2023-10-29 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='authorization',
            new_name='authorization_date',
        ),
    ]
