# Generated by Django 4.2.6 on 2023-10-31 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_remove_sale_discount_remove_sale_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
